name: Full-year calendar
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRIC_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
