name: Terminal metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]} 
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRIC_TOKEN }}
          base: header, metadata, repositories
          plugin_traffic: yes
          plugin_languages: yes
          plugin_languages_ignored: php
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 1
          plugin_lines_history_limit: 1
